Remove the source-repositories workflow
It only ever returns an error, which is undocumented, but seems to be to
do with Git rather than any configuration here.  The steps in the
workflow works locally, just not from the GitHub Action.

```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
```